rtl/host/fx_d2_abi_pkg.sv
rtl/fx_d2_pkg.sv
rtl/common/fx_sync_bits.sv
rtl/common/fx_async_fifo.sv
rtl/numeric/fx_lowbit_decode.sv
rtl/numeric/fx_requantize.sv
rtl/compute/fx_operand_unpacker.sv
rtl/compute/fx_mxu_array.sv
rtl/compute/fx_mxu_cluster.sv
rtl/compute/fx_tensor_engine.sv
rtl/stream/fx_vector_alu32.sv
rtl/stream/fx_rmsnorm32.sv
rtl/stream/fx_softmax32.sv
rtl/stream/fx_rope32.sv
rtl/stream/fx_state_update32.sv
rtl/stream/fx_topk32.sv
rtl/stream/fx_mtp_verify8.sv
rtl/stream/fx_sparse_gather32.sv
rtl/stream/fx_patchify3d.sv
rtl/stream/fx_adaln32.sv
rtl/stream/fx_stream_engine.sv
rtl/memory/fx_scratchpad_banked.sv
rtl/memory/fx_device_mem_router.sv
rtl/host/fx_queue_csr.sv
rtl/host/fx_queue_manager.sv
rtl/top/fusionx_d2_core.sv
