from __future__ import annotations

DEFAULT_SERVING_RECENT_WINDOW = 2048
DEFAULT_RESERVE_FREE_VRAM_MIB = 512
DEFAULT_MAX_STATE_POOL_SIZE = 1
DEFAULT_MAX_PROMPT_TOKENS = 4096
DEFAULT_MAX_GENERATION_TOKENS = 1024
DEFAULT_MAX_BATCHED_TOKENS = 256
DEFAULT_PREFILL_CHUNK_SIZE = 64
DEFAULT_KV_BLOCK_SIZE = 16
DEFAULT_KV_BLOCKS = 1024
