#!/usr/bin/env bash
set -euo pipefail

MODEL_DIR="${MODEL_DIR:-/home/user/models/Qwen3.6-27B}"
QB_DIR="${QB_DIR:-/home/user/models/Qwen3.6-27B-qb4-marlin-fused}"
MODEL_NAME="${MODEL_NAME:-langburst-qwen3.6-27b-q4}"
LANGBURST_ENGINE="${LANGBURST_ENGINE:-native}"
SERVER_PORT="${SERVER_PORT:-8008}"
ENABLE_MTP="${ENABLE_MTP:-${LANGBURST_ENABLE_MTP:-1}}"
MTP_SPECULATIVE_TOKENS="${MTP_SPECULATIVE_TOKENS:-${LANGBURST_MTP_SPECULATIVE_TOKENS:-4}}"
CONTEXT_TIERS="${CONTEXT_TIERS:-4096,65536}"
CONTEXT_TIER_SLOTS="${CONTEXT_TIER_SLOTS:-2,1}"
CONTEXT_WINDOW="${CONTEXT_WINDOW:-${RECENT_WINDOW:-65536}}"
EXCLUSIVE_PREFILL_TOKENS="${EXCLUSIVE_PREFILL_TOKENS:-${LANGBURST_EXCLUSIVE_PREFILL_TOKENS:-}}"
KV_CACHE_DTYPE="${KV_CACHE_DTYPE:-int4_bdr}"
PREFILL_CHUNK_SIZE="${PREFILL_CHUNK_SIZE:-64}"
DECODE_PREFILL_INTERLEAVE_STEPS="${DECODE_PREFILL_INTERLEAVE_STEPS:-16}"
BATCH_WAIT_MS="${BATCH_WAIT_MS:-8}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-256}"
RAW_PREFILL_BLOCK_TOKENS="${RAW_PREFILL_BLOCK_TOKENS:-$PREFILL_CHUNK_SIZE}"
CPU_EMBED="${CPU_EMBED:-0}"
MAX_ACTIVE_REQUESTS="${MAX_ACTIVE_REQUESTS:-3}"
MAX_PREFILL_ROWS_PER_BATCH="${MAX_PREFILL_ROWS_PER_BATCH:-1}"
MAX_QUEUED_REQUESTS="${MAX_QUEUED_REQUESTS:-8}"
MAX_STATE_POOL_SIZE="${MAX_STATE_POOL_SIZE:-$MAX_ACTIVE_REQUESTS}"
MAX_GENERATION_TOKENS="${SERVE_MAX_GENERATION_TOKENS:-1024}"
RESERVE_FREE_VRAM_MIB="${RESERVE_FREE_VRAM_MIB:-256}"
ALLOW_CONTEXT_OVERFLOW="${ALLOW_CONTEXT_OVERFLOW:-${LANGBURST_ALLOW_CONTEXT_OVERFLOW:-1}}"
MARLIN_OUT_CACHE_POLICY="${MARLIN_OUT_CACHE_POLICY:-all}"
PREFIX_CACHE="${PREFIX_CACHE:-${LANGBURST_PREFIX_CACHE:-on}}"
LOG_DIR="${LOG_DIR:-/tmp}"
CPU_EMBED_ARG=()
case "$(printf '%s' "$CPU_EMBED" | tr '[:upper:]' '[:lower:]')" in
  1|true|on|yes) CPU_EMBED_ARG=(--cpu-embed) ;;
esac
MTP_ARG=(--disable-mtp)
case "$(printf '%s' "$ENABLE_MTP" | tr '[:upper:]' '[:lower:]')" in
  1|true|on|yes) MTP_ARG=(--enable-mtp) ;;
esac
CONTEXT_TIER_MAX="$(python - "$CONTEXT_TIERS" <<'PY'
import sys
vals=[int(v.strip()) for v in sys.argv[1].split(",") if v.strip()]
print(max(vals) if vals else 0)
PY
)"
if [ -z "$EXCLUSIVE_PREFILL_TOKENS" ]; then
  EXCLUSIVE_PREFILL_TOKENS="$(python - "$CONTEXT_TIERS" <<'PY'
import sys
vals=sorted(int(v.strip()) for v in sys.argv[1].split(",") if v.strip())
print(vals[0] + 1 if len(vals) > 1 else 0)
PY
)"
fi
if [ "$CONTEXT_TIER_MAX" -gt 0 ] && [ "$CONTEXT_WINDOW" -lt "$CONTEXT_TIER_MAX" ]; then
  CONTEXT_WINDOW="$CONTEXT_TIER_MAX"
fi

cd /home/user/workspace/neurova/langburst
source ~/miniconda3/etc/profile.d/conda.sh
conda activate langburst
source /home/user/workspace/neurova/langburst/scripts/langburst_cuda_env.sh

RESTART_LANGBURST="${RESTART_LANGBURST:-1}"
if [ "$RESTART_LANGBURST" = "1" ] || [ "$RESTART_LANGBURST" = "true" ] || [ "$RESTART_LANGBURST" = "on" ]; then
  if command -v fuser >/dev/null 2>&1; then
    fuser -k "${SERVER_PORT}/tcp" >/dev/null 2>&1 || true
    for _ in $(seq 1 30); do
      if ! ss -ltn | grep -q ":${SERVER_PORT} "; then
        break
      fi
      sleep 0.2
    done
  fi
  mapfile -t EXISTING_PIDS < <(
    ps -eo pid=,args= \
      | awk -v port="$SERVER_PORT" '
          /python -m langburst.server/ && $0 ~ "--port " port "([^0-9]|$)" {print $1}
        '
  )
  if [ "${#EXISTING_PIDS[@]}" -gt 0 ]; then
    kill "${EXISTING_PIDS[@]}" 2>/dev/null || true
    for _ in $(seq 1 30); do
      if ! ss -ltn | grep -q ":${SERVER_PORT} "; then
        break
      fi
      sleep 1
    done
    if ss -ltn | grep -q ":${SERVER_PORT} "; then
      kill -9 "${EXISTING_PIDS[@]}" 2>/dev/null || true
      sleep 1
    fi
  fi
fi

if ! ss -ltn | grep -q ":${SERVER_PORT} "; then
  rm -f "${LOG_DIR}/langburst_server.pid"
  nohup env \
    CUDA_HOME="$CUDA_HOME" \
    CUDACXX="$CUDACXX" \
    PATH="$PATH" \
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH" \
    LANGBURST_REQUIRE_CUDA_EXT="$LANGBURST_REQUIRE_CUDA_EXT" \
    LANGBURST_CONTEXT_WINDOW="$CONTEXT_WINDOW" \
    LANGBURST_CONTEXT_TIERS="$CONTEXT_TIERS" \
    LANGBURST_CONTEXT_TIER_SLOTS="$CONTEXT_TIER_SLOTS" \
    LANGBURST_EXCLUSIVE_PREFILL_TOKENS="$EXCLUSIVE_PREFILL_TOKENS" \
    LANGBURST_ALLOW_CONTEXT_OVERFLOW="$ALLOW_CONTEXT_OVERFLOW" \
    LANGBURST_PREFILL_CHUNK_SIZE="$PREFILL_CHUNK_SIZE" \
    LANGBURST_MAX_PREFILL_ROWS_PER_BATCH="$MAX_PREFILL_ROWS_PER_BATCH" \
    LANGBURST_DECODE_PREFILL_INTERLEAVE_STEPS="$DECODE_PREFILL_INTERLEAVE_STEPS" \
    LANGBURST_BATCH_WAIT_MS="$BATCH_WAIT_MS" \
    LANGBURST_MAX_NUM_BATCHED_TOKENS="$MAX_NUM_BATCHED_TOKENS" \
    LANGBURST_MAX_ACTIVE_REQUESTS="$MAX_ACTIVE_REQUESTS" \
    LANGBURST_MAX_QUEUED_REQUESTS="$MAX_QUEUED_REQUESTS" \
    LANGBURST_MAX_STATE_POOL_SIZE="$MAX_STATE_POOL_SIZE" \
    LANGBURST_MAX_GENERATION_TOKENS="$MAX_GENERATION_TOKENS" \
    LANGBURST_SERVE_BATCH="${LANGBURST_SERVE_BATCH:-1}" \
    LANGBURST_BATCH_STATE_ARENA="${LANGBURST_BATCH_STATE_ARENA:-auto}" \
    LANGBURST_PAGED_KV="${LANGBURST_PAGED_KV:-1}" \
    LANGBURST_PAGED_KV_MIRROR="${LANGBURST_PAGED_KV_MIRROR:-0}" \
    LANGBURST_PAGED_KV_SHADOW="${LANGBURST_PAGED_KV_SHADOW:-1}" \
    LANGBURST_PAGED_ATTENTION_KERNELS="${LANGBURST_PAGED_ATTENTION_KERNELS:-1}" \
    LANGBURST_PAGED_PREFILL_BLOCK="${LANGBURST_PAGED_PREFILL_BLOCK:-1}" \
    LANGBURST_SHORT_PREFILL_SDPA_TOKENS="${LANGBURST_SHORT_PREFILL_SDPA_TOKENS:-2048}" \
    LANGBURST_SHORT_PREFILL_SDPA_MIN_FREE_MIB="${LANGBURST_SHORT_PREFILL_SDPA_MIN_FREE_MIB:-384}" \
    LANGBURST_ATTENTION_RECENT_TOKENS="${LANGBURST_ATTENTION_RECENT_TOKENS:-32}" \
    LANGBURST_PAGED_ATTENTION_BACKEND="${LANGBURST_PAGED_ATTENTION_BACKEND:-flash}" \
    LANGBURST_INT4_KV_LAYOUT="${LANGBURST_INT4_KV_LAYOUT:-tiled}" \
    LANGBURST_MARLIN_OUT_CACHE_POLICY="$MARLIN_OUT_CACHE_POLICY" \
    LANGBURST_MARLIN_OUT_CACHE_MAX_BATCH="${LANGBURST_MARLIN_OUT_CACHE_MAX_BATCH:-4}" \
    LANGBURST_MARLIN_CACHE_MAX_MIB="${LANGBURST_MARLIN_CACHE_MAX_MIB:-32}" \
    LANGBURST_MARLIN_CACHE_MIN_FREE_MIB="${LANGBURST_MARLIN_CACHE_MIN_FREE_MIB:-256}" \
    LANGBURST_MARLIN_DIRECT_MAX_BATCH="${LANGBURST_MARLIN_DIRECT_MAX_BATCH:-256}" \
    LANGBURST_LOWBIT_ROWS_PER_CTA="${LANGBURST_LOWBIT_ROWS_PER_CTA:-4}" \
    LANGBURST_CUDA_GRAPH="${LANGBURST_CUDA_GRAPH:-0}" \
    LANGBURST_MARLIN_INTERNAL_ARGMAX="${LANGBURST_MARLIN_INTERNAL_ARGMAX:-1}" \
    LANGBURST_VERIFY_FULL_LOGITS="${LANGBURST_VERIFY_FULL_LOGITS:-0}" \
    LANGBURST_GDN_RECURRENT_NORM_GATE_FUSED="${LANGBURST_GDN_RECURRENT_NORM_GATE_FUSED:-0}" \
    LANGBURST_GDN_SPEC_NORM_GATE_FUSED="${LANGBURST_GDN_SPEC_NORM_GATE_FUSED:-0}" \
    LANGBURST_GDN_BA_LOWBIT_PAIR="${LANGBURST_GDN_BA_LOWBIT_PAIR:-1}" \
    LANGBURST_MLP_TENSORCORE_DOWN_SILU_A="${LANGBURST_MLP_TENSORCORE_DOWN_SILU_A:-1}" \
    LANGBURST_MLP_SCALAR_STREAMING_DEBUG="${LANGBURST_MLP_SCALAR_STREAMING_DEBUG:-0}" \
    LANGBURST_SPEC_TRAJECTORY_COPY_CUDA="${LANGBURST_SPEC_TRAJECTORY_COPY_CUDA:-1}" \
    LANGBURST_MTP_MAX_DRAFT="${LANGBURST_MTP_MAX_DRAFT:-4}" \
    LANGBURST_MTP_DRAFT_CANDIDATES="${LANGBURST_MTP_DRAFT_CANDIDATES:-4}" \
    LANGBURST_MTP_MAX_DRAFT_BY_ACTIVE="${LANGBURST_MTP_MAX_DRAFT_BY_ACTIVE:-2:1}" \
    LANGBURST_MTP_LEGACY_LIST_CACHE="${LANGBURST_MTP_LEGACY_LIST_CACHE:-0}" \
    LANGBURST_MTP_LOCAL_TKH_ATTENTION="${LANGBURST_MTP_LOCAL_TKH_ATTENTION:-1}" \
    LANGBURST_MTP_BATCH_PROPOSER="${LANGBURST_MTP_BATCH_PROPOSER:-1}" \
    LANGBURST_MTP_FC_SPLIT="${LANGBURST_MTP_FC_SPLIT:-0}" \
    LANGBURST_MTP_SKIP_AFTER_REJECT="${LANGBURST_MTP_SKIP_AFTER_REJECT:-0}" \
    LANGBURST_MTP_ADAPTIVE="${LANGBURST_MTP_ADAPTIVE:-0}" \
    LANGBURST_MTP_MIN_FREE_VRAM_MIB="${LANGBURST_MTP_MIN_FREE_VRAM_MIB:-128}" \
    LANGBURST_REQUEST_TIMEOUT_S="${LANGBURST_REQUEST_TIMEOUT_S:-300}" \
    LANGBURST_DEFAULT_MAX_TOKENS="$MAX_GENERATION_TOKENS" \
    LANGBURST_SUPPRESS_THINK_TOKENS="${LANGBURST_SUPPRESS_THINK_TOKENS:-0}" \
    LANGBURST_REPETITION_STOP_NGRAM_SIZE="${LANGBURST_REPETITION_STOP_NGRAM_SIZE:-8}" \
    LANGBURST_REPETITION_STOP_REPEATS="${LANGBURST_REPETITION_STOP_REPEATS:-4}" \
    LANGBURST_TRIM_CACHE_AFTER_REQUEST="${LANGBURST_TRIM_CACHE_AFTER_REQUEST:-${LANGBURST_TRIM_CACHE_DURING_PREFILL:-1}}" \
    LANGBURST_TRIM_CACHE_FREE_BELOW_MIB="${LANGBURST_TRIM_CACHE_FREE_BELOW_MIB:-1024}" \
    LANGBURST_TRIM_MODEL_CACHE_BEFORE_PREFILL="${LANGBURST_TRIM_MODEL_CACHE_BEFORE_PREFILL:-1}" \
    LANGBURST_TRIM_MODEL_CACHE_PREFILL_FREE_BELOW_MIB="${LANGBURST_TRIM_MODEL_CACHE_PREFILL_FREE_BELOW_MIB:-1024}" \
    LANGBURST_PREFIX_CACHE_MAX_ENTRIES="${LANGBURST_PREFIX_CACHE_MAX_ENTRIES:-2}" \
    LANGBURST_PREFIX_CACHE_MAX_TOKENS="${LANGBURST_PREFIX_CACHE_MAX_TOKENS:-16384}" \
    LANGBURST_PREFIX_CACHE_MIN_FREE_MIB="${LANGBURST_PREFIX_CACHE_MIN_FREE_MIB:-768}" \
    LANGBURST_PREFIX_CACHE_MIN_FREE_BLOCKS="${LANGBURST_PREFIX_CACHE_MIN_FREE_BLOCKS:-512}" \
    LANGBURST_RAW_PREFILL_BLOCK_TOKENS="$RAW_PREFILL_BLOCK_TOKENS" \
    PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True \
    python -m langburst.server \
      --engine "$LANGBURST_ENGINE" \
      --adapter qwen36 \
      --hf-model "$MODEL_DIR" \
      --qb-model "$QB_DIR" \
      --model-name "$MODEL_NAME" \
      --host 0.0.0.0 \
      --port "$SERVER_PORT" \
      "${MTP_ARG[@]}" \
      --mtp-speculative-tokens "$MTP_SPECULATIVE_TOKENS" \
      --recent-window "$CONTEXT_WINDOW" \
      --max-active-requests "$MAX_ACTIVE_REQUESTS" \
      --max-queued-requests "$MAX_QUEUED_REQUESTS" \
      --max-state-pool-size "$MAX_STATE_POOL_SIZE" \
      --max-generation-tokens "$MAX_GENERATION_TOKENS" \
      --max-num-batched-tokens "$MAX_NUM_BATCHED_TOKENS" \
      --prefill-chunk-size "$PREFILL_CHUNK_SIZE" \
      --max-prefill-rows-per-batch "$MAX_PREFILL_ROWS_PER_BATCH" \
      --exclusive-prefill-tokens "$EXCLUSIVE_PREFILL_TOKENS" \
      --reserve-free-vram-mib "$RESERVE_FREE_VRAM_MIB" \
      --context-tiers "$CONTEXT_TIERS" \
      --context-tier-slots "$CONTEXT_TIER_SLOTS" \
      "$(case "$(printf '%s' "$ALLOW_CONTEXT_OVERFLOW" | tr '[:upper:]' '[:lower:]')" in 1|true|on|yes) printf '%s' --allow-context-overflow ;; *) printf '%s' --no-allow-context-overflow ;; esac)" \
      "${CPU_EMBED_ARG[@]}" \
      --kv-cache-dtype "$KV_CACHE_DTYPE" \
      --prefix-cache "$PREFIX_CACHE" \
    > "${LOG_DIR}/langburst_server.log" 2>&1 < /dev/null &
  SERVER_PID="$!"
  echo "$SERVER_PID" > "${LOG_DIR}/langburst_server.pid"
  sleep 1
  if ! kill -0 "$SERVER_PID" 2>/dev/null; then
    echo "langburst server exited during startup; see ${LOG_DIR}/langburst_server.log" >&2
    tail -n 120 "${LOG_DIR}/langburst_server.log" >&2 || true
    exit 1
  fi
fi

for _ in $(seq 1 120); do
  if curl -fsS "http://127.0.0.1:${SERVER_PORT}/v1/models" >/dev/null 2>&1; then
    break
  fi
  if [ -f "${LOG_DIR}/langburst_server.pid" ]; then
    SERVER_PID="$(cat "${LOG_DIR}/langburst_server.pid" 2>/dev/null || true)"
    if [ -n "$SERVER_PID" ] && ! kill -0 "$SERVER_PID" 2>/dev/null; then
      echo "langburst server exited before readiness; see ${LOG_DIR}/langburst_server.log" >&2
      tail -n 120 "${LOG_DIR}/langburst_server.log" >&2 || true
      exit 1
    fi
  fi
  sleep 1
done

if ! curl -fsS "http://127.0.0.1:${SERVER_PORT}/v1/models" >/dev/null; then
  echo "langburst server did not become ready; see ${LOG_DIR}/langburst_server.log" >&2
  exit 1
fi

echo "LangBurst: http://127.0.0.1:${SERVER_PORT}/v1"
curl -fsS "http://127.0.0.1:${SERVER_PORT}/v1/models"
echo
